version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=ges-compte
      - DB_USERNAME=yateddene
      - DB_PASSWORD=faye0000
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ges-compte
      POSTGRES_USER: yateddene
      POSTGRES_PASSWORD: faye0000
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: